- name: Setup SSL certificates for proxy
  hosts: proxy
  become: true
  roles:
    - role: ssl
      vars:
        domain: "{{ proxy_domain }}"
      tags: ssl

- name: Setup SSL certificates for explorer
  hosts: explorer
  become: true
  roles:
    - role: ssl
      vars:
        domain: "*.{{ explorer_domain }}"
      tags: ssl
