- name: Setup SSL certificates for proxy
  hosts: proxy
  become: true
  roles:
    - role: ssl
      vars:
        domain: "{{ proxy_domain }}"
        ssl_src: "files/ssl/proxy"

- name: Setup SSL certificates for explorer
  hosts: explorer
  become: true
  roles:
    - role: ssl
      vars:
        domain: "*.{{ explorer_domain }}"
        ssl_src: "files/ssl/explorer"
