- name: Create ABIs dir
  file:
    path: "{{ base_path }}/skale-proxy/abi"
    state: directory

- name: Copy ABIs to proxy
  copy:
    src: "files/abi.json"
    dest: "{{ base_path }}/skale-proxy/data/abi.json"

- name: Copy SSL certificate file (proxy)
  copy:
    src: "{{ base_path }}/ssl/{{ inventory_hostname }}/{{ item.src }}"
    dest: "{{ base_path }}/skale-proxy/data/{{ item.dest }}"
    remote_src: true
  loop:
    - { src: "fullchain.pem", dest: "server.crt" }
    - { src: "privkey.pem", dest: "server.key" }

- name: Update containers
  command: "docker-compose pull"
  args:
    chdir: "{{ base_path }}/skale-proxy"

- name: Run proxy
  command: "bash scripts/run_proxy.sh"
  environment:
    ETH_ENDPOINT: "{{ eth_endpoint }}"
    FIRST_SCHAIN_ID: "{{ groups['proxy'].index(inventory_hostname) * 100 }}"
    LAST_SCHAIN_ID: "{{ ( groups['proxy'].index(inventory_hostname) + 1) * 100 }}"
    NETWORK_NAME: "{{ network_name }}"
    HEARTBEAT_URL: "{{ heartbeat_url }}"
  args:
    chdir: "{{ base_path }}/skale-proxy"
