- import_tasks: install.yaml
  when: local_src is not defined or local_src
  tags: certbot_install

- import_tasks: do.yaml
  when: local_src is not defined or local_src
  tags: do_configure

- import_tasks: ensure.yaml
  when: local_src is not defined or local_src
  tags: certbot_generate

- import_tasks: hook.yaml
  when: local_src is not defined or local_src
  tags: certbot_generate

- import_tasks: prepare.yaml
  when: local_src is not defined or local_src
  tags: ssl_prepare

- import_tasks: sync.yaml
  when: local_src is defined and not local_src
  tags: ssl_prepare
